[advisories]
yanked = "deny"
unmaintained = "workspace"
unsound = "workspace"

[bans]
multiple-versions = "deny"
wildcards = "deny"

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "MIT",
    "Unicode-3.0",
]
confidence-threshold = 0.8

[licenses.private]
ignore = false

[sources]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "rev"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
